import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={`${inter.className} h-full`}>
        <Header />

        {children}
      </body>
    </html>
  );
}
